### ISSUE TITLE
Wont start up

### ISSUE THREAD

**Issue by unze2unze4** [hairr/chatbot#3]
Im getting this error when i try to start it up, and the bot doesn't log in. Im very new to python, I literally downloaded it 5 minutes ago. I omitted the password.

```
Traceback (most recent call last):
  File "C:\Stuff\Portmanteu.py", line 31, in <module>
    bot = MyBot('portmanteu', '#########', 'http://slime-rancher-fanon.wikia.com')
  File "C:\Stuff\Portmanteu.py", line 9, in __init__
    site)
  File "C:\Python27\lib\site-packages\chatbot.py", line 369, in __init__
    self.c = Client(username, password, site)
  File "C:\Python27\lib\site-packages\chatbot.py", line 144, in __init__
    self.settings["port"] = data["nodePort"]
KeyError: 'nodePort'
```

**Comment by T3CHNOCIDE** [comment]
Unfortunately this bot frame work is 3 years old and has missed out on some major Wikia side updates. I don't want to self promote, but I've worked on a Wikia chat bot using this bot and Sactage's bot as major influences. You can see it here: https://github.com/T3CHNOCIDE/Dugong-Client. There's also Vic's bot, however it's also missed out on a major update to the Wikia chat so I don't know if it works any more: https://github.com/Vicyorus/VicBot.
